---
title: Echo Sierra Studio
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
    permalink: /:year/:month/:day/:title:output_ext
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    has_comments: true
    image: ''
    description: ''
- scope:
    path: ''
    type: works
  values:
    weight: 50
    image: ''
    link: ''
    title_bold: ''
    image_width: ''
    image_height: ''
has_comments: true
disqus: https-esstudio-site
feedburner: https://feeds.feedburner.com/echosierrastudio
share:
- facebook
- twitter
- tumblr
- pinterest
- reddit
- google
- tumblr
- email
- pinterest
- linkedin
- xing
- whatsapp
- hackernews
- vk
- telegram
volledige-titel: Echo Sierra Studio
image_src: "/assets/img/image_src.png"
logo: "/assets/img/image_src.png"
keywords: Polyism Studio Sem Postma Echo Sierra Studio Web Software Code Programming
  Hub
exclude:
- vendor
description: Web, app and tooling development and graphic design studio. View all
  websites made by Echo Sierra Studio and contact us if your interested.
theme_color: "#fb5353"
disqus: https-esstudio-site
baseurl: 
abbrv: ESS
dribbble_username: es_studio
facebook_username: ES-Studio-2052606714783317
flickr_username: es_studio
github_username: LesterGallagher
instagram_username: 
linkedin_username: 
pinterest_username: eestudio0040
twitter_username: esstudio_site
youtube_username: 9Wereld
disqus_username: https://disqus.com/by/echosierrastudio/
googleplus_username: 
rss: true
facebook:
  app_id: 1015809515263840
  publisher: 2052606714783317
  admins: 100028399686104
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
twitter:
  username: esstudio_site
sass:
  style: compressed
  sass_dir: _sass
url: https://esstudio.site
enforce_ssl: esstudio.site
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-sitemap
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
theme: minima
author: Sem Postma
designer: Sem Postma
lang: en
humanstxt_author:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
humanstxt_designer:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
google_analytics: UA-90014538-4
