---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://maker.ifttt.com/trigger/forestry/with/key/fuhBM33MbuVc8JP5wABOTjQVESdNiQe0CjNlxG1QuA9
sections:
- type: directory
  path: _uploads
  label: Uploads
  create: all
  match: "**/*"
- type: directory
  path: _works
  label: Works
  create: documents
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: _uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
